# This is a basic workflow to help you get started with Actions

name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ijn35807/docker-image-autobuild:latest
    - name: Push the Docker image
      run: docker login -u someeshfanda -p ${{ secrets.DOCKER_TOKEN }} && docker push ijn35807/docker-image-autobuild:latest
